// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package com.example.proto;

public final class Example {
  private Example() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_proto_GithubApi_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_proto_GithubApi_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rexample.proto\022\021com.example.proto\"\234\006\n\tG" +
      "ithubApi\022\030\n\020current_user_url\030\001 \001(\t\022,\n$cu" +
      "rrent_user_authorizations_html_url\030\002 \001(\t" +
      "\022\032\n\022authorizations_url\030\003 \001(\t\022\027\n\017code_sea" +
      "rch_url\030\004 \001(\t\022\031\n\021commit_search_url\030\005 \001(\t" +
      "\022\022\n\nemails_url\030\006 \001(\t\022\022\n\nemojis_url\030\007 \001(\t" +
      "\022\022\n\nevents_url\030\010 \001(\t\022\021\n\tfeeds_url\030\t \001(\t\022" +
      "\025\n\rfollowers_url\030\n \001(\t\022\025\n\rfollowing_url\030" +
      "\013 \001(\t\022\021\n\tgists_url\030\014 \001(\t\022\017\n\007hub_url\030\r \001(" +
      "\t\022\030\n\020issue_search_url\030\016 \001(\t\022\022\n\nissues_ur" +
      "l\030\017 \001(\t\022\020\n\010keys_url\030\020 \001(\t\022\031\n\021notificatio" +
      "ns_url\030\021 \001(\t\022%\n\035organization_repositorie" +
      "s_url\030\022 \001(\t\022\030\n\020organization_url\030\023 \001(\t\022\030\n" +
      "\020public_gists_url\030\024 \001(\t\022\026\n\016rate_limit_ur" +
      "l\030\025 \001(\t\022\026\n\016repository_url\030\026 \001(\t\022\035\n\025repos" +
      "itory_search_url\030\027 \001(\t\022%\n\035current_user_r" +
      "epositories_url\030\030 \001(\t\022\023\n\013starred_url\030\031 \001" +
      "(\t\022\031\n\021starred_gists_url\030\032 \001(\t\022\020\n\010team_ur" +
      "l\030\033 \001(\t\022\020\n\010user_url\030\034 \001(\t\022\036\n\026user_organi" +
      "zations_url\030\035 \001(\t\022\035\n\025user_repositories_u" +
      "rl\030\036 \001(\t\022\027\n\017user_search_url\030\037 \001(\tB\005P\001\272\002\000" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_example_proto_GithubApi_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_proto_GithubApi_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_proto_GithubApi_descriptor,
        new java.lang.String[] { "CurrentUserUrl", "CurrentUserAuthorizationsHtmlUrl", "AuthorizationsUrl", "CodeSearchUrl", "CommitSearchUrl", "EmailsUrl", "EmojisUrl", "EventsUrl", "FeedsUrl", "FollowersUrl", "FollowingUrl", "GistsUrl", "HubUrl", "IssueSearchUrl", "IssuesUrl", "KeysUrl", "NotificationsUrl", "OrganizationRepositoriesUrl", "OrganizationUrl", "PublicGistsUrl", "RateLimitUrl", "RepositoryUrl", "RepositorySearchUrl", "CurrentUserRepositoriesUrl", "StarredUrl", "StarredGistsUrl", "TeamUrl", "UserUrl", "UserOrganizationsUrl", "UserRepositoriesUrl", "UserSearchUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
