// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package com.example.proto;

public interface GithubApiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.proto.GithubApi)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string current_user_url = 1;</code>
   */
  java.lang.String getCurrentUserUrl();
  /**
   * <code>string current_user_url = 1;</code>
   */
  com.google.protobuf.ByteString
      getCurrentUserUrlBytes();

  /**
   * <code>string current_user_authorizations_html_url = 2;</code>
   */
  java.lang.String getCurrentUserAuthorizationsHtmlUrl();
  /**
   * <code>string current_user_authorizations_html_url = 2;</code>
   */
  com.google.protobuf.ByteString
      getCurrentUserAuthorizationsHtmlUrlBytes();

  /**
   * <code>string authorizations_url = 3;</code>
   */
  java.lang.String getAuthorizationsUrl();
  /**
   * <code>string authorizations_url = 3;</code>
   */
  com.google.protobuf.ByteString
      getAuthorizationsUrlBytes();

  /**
   * <code>string code_search_url = 4;</code>
   */
  java.lang.String getCodeSearchUrl();
  /**
   * <code>string code_search_url = 4;</code>
   */
  com.google.protobuf.ByteString
      getCodeSearchUrlBytes();

  /**
   * <code>string commit_search_url = 5;</code>
   */
  java.lang.String getCommitSearchUrl();
  /**
   * <code>string commit_search_url = 5;</code>
   */
  com.google.protobuf.ByteString
      getCommitSearchUrlBytes();

  /**
   * <code>string emails_url = 6;</code>
   */
  java.lang.String getEmailsUrl();
  /**
   * <code>string emails_url = 6;</code>
   */
  com.google.protobuf.ByteString
      getEmailsUrlBytes();

  /**
   * <code>string emojis_url = 7;</code>
   */
  java.lang.String getEmojisUrl();
  /**
   * <code>string emojis_url = 7;</code>
   */
  com.google.protobuf.ByteString
      getEmojisUrlBytes();

  /**
   * <code>string events_url = 8;</code>
   */
  java.lang.String getEventsUrl();
  /**
   * <code>string events_url = 8;</code>
   */
  com.google.protobuf.ByteString
      getEventsUrlBytes();

  /**
   * <code>string feeds_url = 9;</code>
   */
  java.lang.String getFeedsUrl();
  /**
   * <code>string feeds_url = 9;</code>
   */
  com.google.protobuf.ByteString
      getFeedsUrlBytes();

  /**
   * <code>string followers_url = 10;</code>
   */
  java.lang.String getFollowersUrl();
  /**
   * <code>string followers_url = 10;</code>
   */
  com.google.protobuf.ByteString
      getFollowersUrlBytes();

  /**
   * <code>string following_url = 11;</code>
   */
  java.lang.String getFollowingUrl();
  /**
   * <code>string following_url = 11;</code>
   */
  com.google.protobuf.ByteString
      getFollowingUrlBytes();

  /**
   * <code>string gists_url = 12;</code>
   */
  java.lang.String getGistsUrl();
  /**
   * <code>string gists_url = 12;</code>
   */
  com.google.protobuf.ByteString
      getGistsUrlBytes();

  /**
   * <code>string hub_url = 13;</code>
   */
  java.lang.String getHubUrl();
  /**
   * <code>string hub_url = 13;</code>
   */
  com.google.protobuf.ByteString
      getHubUrlBytes();

  /**
   * <code>string issue_search_url = 14;</code>
   */
  java.lang.String getIssueSearchUrl();
  /**
   * <code>string issue_search_url = 14;</code>
   */
  com.google.protobuf.ByteString
      getIssueSearchUrlBytes();

  /**
   * <code>string issues_url = 15;</code>
   */
  java.lang.String getIssuesUrl();
  /**
   * <code>string issues_url = 15;</code>
   */
  com.google.protobuf.ByteString
      getIssuesUrlBytes();

  /**
   * <code>string keys_url = 16;</code>
   */
  java.lang.String getKeysUrl();
  /**
   * <code>string keys_url = 16;</code>
   */
  com.google.protobuf.ByteString
      getKeysUrlBytes();

  /**
   * <code>string notifications_url = 17;</code>
   */
  java.lang.String getNotificationsUrl();
  /**
   * <code>string notifications_url = 17;</code>
   */
  com.google.protobuf.ByteString
      getNotificationsUrlBytes();

  /**
   * <code>string organization_repositories_url = 18;</code>
   */
  java.lang.String getOrganizationRepositoriesUrl();
  /**
   * <code>string organization_repositories_url = 18;</code>
   */
  com.google.protobuf.ByteString
      getOrganizationRepositoriesUrlBytes();

  /**
   * <code>string organization_url = 19;</code>
   */
  java.lang.String getOrganizationUrl();
  /**
   * <code>string organization_url = 19;</code>
   */
  com.google.protobuf.ByteString
      getOrganizationUrlBytes();

  /**
   * <code>string public_gists_url = 20;</code>
   */
  java.lang.String getPublicGistsUrl();
  /**
   * <code>string public_gists_url = 20;</code>
   */
  com.google.protobuf.ByteString
      getPublicGistsUrlBytes();

  /**
   * <code>string rate_limit_url = 21;</code>
   */
  java.lang.String getRateLimitUrl();
  /**
   * <code>string rate_limit_url = 21;</code>
   */
  com.google.protobuf.ByteString
      getRateLimitUrlBytes();

  /**
   * <code>string repository_url = 22;</code>
   */
  java.lang.String getRepositoryUrl();
  /**
   * <code>string repository_url = 22;</code>
   */
  com.google.protobuf.ByteString
      getRepositoryUrlBytes();

  /**
   * <code>string repository_search_url = 23;</code>
   */
  java.lang.String getRepositorySearchUrl();
  /**
   * <code>string repository_search_url = 23;</code>
   */
  com.google.protobuf.ByteString
      getRepositorySearchUrlBytes();

  /**
   * <code>string current_user_repositories_url = 24;</code>
   */
  java.lang.String getCurrentUserRepositoriesUrl();
  /**
   * <code>string current_user_repositories_url = 24;</code>
   */
  com.google.protobuf.ByteString
      getCurrentUserRepositoriesUrlBytes();

  /**
   * <code>string starred_url = 25;</code>
   */
  java.lang.String getStarredUrl();
  /**
   * <code>string starred_url = 25;</code>
   */
  com.google.protobuf.ByteString
      getStarredUrlBytes();

  /**
   * <code>string starred_gists_url = 26;</code>
   */
  java.lang.String getStarredGistsUrl();
  /**
   * <code>string starred_gists_url = 26;</code>
   */
  com.google.protobuf.ByteString
      getStarredGistsUrlBytes();

  /**
   * <code>string team_url = 27;</code>
   */
  java.lang.String getTeamUrl();
  /**
   * <code>string team_url = 27;</code>
   */
  com.google.protobuf.ByteString
      getTeamUrlBytes();

  /**
   * <code>string user_url = 28;</code>
   */
  java.lang.String getUserUrl();
  /**
   * <code>string user_url = 28;</code>
   */
  com.google.protobuf.ByteString
      getUserUrlBytes();

  /**
   * <code>string user_organizations_url = 29;</code>
   */
  java.lang.String getUserOrganizationsUrl();
  /**
   * <code>string user_organizations_url = 29;</code>
   */
  com.google.protobuf.ByteString
      getUserOrganizationsUrlBytes();

  /**
   * <code>string user_repositories_url = 30;</code>
   */
  java.lang.String getUserRepositoriesUrl();
  /**
   * <code>string user_repositories_url = 30;</code>
   */
  com.google.protobuf.ByteString
      getUserRepositoriesUrlBytes();

  /**
   * <code>string user_search_url = 31;</code>
   */
  java.lang.String getUserSearchUrl();
  /**
   * <code>string user_search_url = 31;</code>
   */
  com.google.protobuf.ByteString
      getUserSearchUrlBytes();
}
